#pragma once

// SET THESE VALUES TO BE ON 200 GRID
// MAKES GRID WORK OUT 
// MAKES EVEN 100 INCREMENTS TO EDGE
#define SCREEN_WIDTH				2400
#define SCREEN_HEIGHT				1600
#define GRAPHIC_AREA_WIDTH			((float)SCREEN_WIDTH)
#define GRAPHIC_AREA_HEIGHT			((float)SCREEN_HEIGHT)
#define GRAPHIC_AREA_HALF_WIDTH		((float)(SCREEN_WIDTH >> 1))
#define GRAPHIC_AREA_HALF_HEIGHT	((float)(SCREEN_HEIGHT >> 1))
#define ASPECT_RATIO				((float)SCREEN_WIDTH/(float)SCREEN_HEIGHT)
enum ImageJustify
{
	NOTHING = 0,
	FLIP_IMAGE = 1, // flip vertically
	CENTER_IMAGE = 2, // center the image at 0,0,0
	CENTER_FLIP_IMAGE = 3, // center and flip
	BOTTOM_IMAGE = 4, // center the bottom of the image at 0,0,0
	BOTTOM_FLIP_IMAGE = 5,
	TOP_IMAGE = 6, // center the top of the image at 0,0,0
	TOP_FLIP_IMAGE = 7
};

enum VertexExchange
{
	XYZ = 0,
	XZY = 1,
	YXZ = 2,
	YZX = 3,
	ZXY = 4,
	ZYX = 5
};

enum RenderStyles
{
	WIREFRAME,
	WIREFRAMEwPERSPECTIVE,
	RASTERIZE,
	RASTERIZEwPERSPECTIVE,
	RAY_TRACE,
	RAY_TRACE_Z
};

#define WM_CONTENT_MESSAGE		32771
#define WM_CAMERA_MESSAGE		32772
#define WM_LIGHTING_MESSAGE		32773
#define WM_OBJECT_MESSAGE		32774
#define WM_VIDEO_MESSAGE		32775
#define WM_SCRIPT_MESSAGE		32776

#define WM_CONTENT_FRAME_RATE_CHANGE			0
#define WM_CONTENT_BACKGROUND_COLOR_CHANGE		1
#define WM_CONTENT_JSON_FILENAME				2
#define WM_CONTENT_GRID_TOGGLE					3
#define WM_CONTENT_AXIS_TOGGLE					4
#define WM_CONTENT_RENDER_STYLE_CHANGE			5
#define WM_CONTENT_HEX_CORRIDOR					6

#define WM_CAMERA_CHANGED						0
#define WM_CAMERA_X_CHANGED						1
#define WM_CAMERA_Y_CHANGED						2
#define WM_CAMERA_Z_CHANGED						3
#define WM_CAMERA_TARGET_X_CHANGED				4
#define WM_CAMERA_TARGET_Y_CHANGED				5
#define WM_CAMERA_TARGET_Z_CHANGED				6

#define WM_LIGHT_CHANGED						0
#define WM_LIGHT_STATUS_TOGGLE					1
#define WM_LIGHT_X_CHANGED						2
#define WM_LIGHT_Y_CHANGED						3
#define WM_LIGHT_Z_CHANGED						4
#define WM_LIGHT_TARGET_X_CHANGED				5
#define WM_LIGHT_TARGET_Y_CHANGED				6
#define WM_LIGHT_TARGET_Z_CHANGED				7
#define WM_LIGHT_COLOR_CHANGED					8
#define WM_LIGHT_INTENSITY_CHANGED				9
#define WM_LIGHT_AMBIENT_COLOR_CHANGED			10
#define WM_LIGHT_AMBIENT_INTENSITY_CHANGED		11
#define WM_LIGHT_BEAM_CONE_ANGLE_CHANGED		12

#define WM_OBJECT_CHANGED						0
#define WM_OBJECT_X_CHANGED						1
#define WM_OBJECT_Y_CHANGED						2
#define WM_OBJECT_Z_CHANGED						3
#define WM_OBJECT_PITCH_CHANGED					4
#define WM_OBJECT_YAW_CHANGED					5
#define WM_OBJECT_ROLL_CHANGED					6
